Create task_7_e
Invader1719/Contest_7_upd pull request #2
Opened 2024-05-20 13:42 UTC by Invader1719

2024-05-20 20:53 UTC, Polinakleidman requested changes

2024-05-20 20:53 UTC, Polinakleidman commented on task_7_e
> +void Dfs(GraphInfo& ggg, int vertex, int parent, int paredge) {
dfs должны быть методом класса

2024-05-20 20:53 UTC, Polinakleidman commented on task_7_e
> +struct GraphInfo {
struct ->class, и сначала должны идти методы, а потом поля

2024-05-20 20:53 UTC, Polinakleidman commented on task_7_e
> +  int nnn;
нейминги непонятные

2024-05-20 21:03 UTC, Invader1719 commented on task_7_e
> +struct GraphInfo {
Это глобальные константы, без них методы не работают

2024-05-21 19:58 UTC, Polinakleidman commented on task_7_e
> +struct GraphInfo {
я про поля и методы внутри класса

2024-05-21 19:59 UTC, Polinakleidman approved these changes
В целом ок, но на будущее сначала должны идти публичные методы, потом публичные поля, потом приватные методы, потом приватные поля

2024-05-21 20:01 UTC, merged